// CREATE CLASSROOM
export const ADD_CLASSROOM_REQUEST = 'ADD_CLASSROOM_REQUEST'
export const ADD_CLASSROOM_SUCCESS = 'ADD_CLASSROOM_SUCCESS'
export const ADD_CLASSROOM_FAILURE = 'ADD_CLASSROOM_FAILURE'

// GET ALL CURRENT TEACHERS CLASSROOMS
export const GET_ALL_CURRENT_TEACHERS_CLASSROOMS_REQUEST =
  'GET_ALL_CURRENT_TEACHERS_CLASSROOMS_REQUEST'
export const GET_ALL_CURRENT_TEACHERS_CLASSROOMS_SUCCESS =
  'GET_ALL_CURRENT_TEACHERS_CLASSROOMS_SUCCESS'
export const GET_ALL_CURRENT_TEACHERS_CLASSROOMS_FAILURE =
  'GET_ALL_CURRENT_TEACHERS_CLASSROOMS_FAILURE'

// VERIFY INVITE CODE
export const VERIFY_INVITE_CODE_REQUEST = 'VERIFY_INVITE_CODE_REQUEST'
export const VERIFY_INVITE_CODE_SUCCESS = 'VERIFY_INVITE_CODE_SUCCESS'
export const VERIFY_INVITE_CODE_FAILURE = 'VERIFY_INVITE_CODE_FAILURE'

export const GET_CLASSROOM_REQUEST = 'GET_CLASSROOM_REQUEST'
export const GET_CLASSROOM_SUCCESS = 'GET_CLASSROOM_SUCCESS'
export const GET_CLASSROOM_FAILURE = 'GET_CLASSROOM_FAILURE'
