export const SET_ACCOUNT_TYPE = 'SET_ACCOUNT_TYPE'

// register with email
export const REGISTER_WITH_EMAIL_REQUEST = 'REGISTER_WITH_EMAIL_REQUEST'
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS'
export const REGISTER_WITH_EMAIL_FAILURE = 'REGISTER_WITH_EMAIL_FAILURE'

export const CHECK_FOR_EXISTING_EMAIL_REQUEST =
  'CHECK_FOR_EXISTING_EMAIL_REQUEST'
export const CHECK_FOR_EXISTING_EMAIL_SUCCESS =
  'CHECK_FOR_EXISTING_EMAIL_SUCCESS'
export const CHECK_FOR_EXISTING_EMAIL_FAIL = 'CHECK_FOR_EXISTING_EMAIL_FAIL'
