export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

// login user
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
// export const USER_LOGOUT = 'USER_LOGOUT'

// logout user
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'

export const SET_GOOGLE_ACCOUNT_TYPE = 'SET_GOOGLE_ACCOUNT_TYPE'

// veryify logged in user after login
export const VERIFY_LOGGED_IN_USER_REQUEST = 'VERIFY_LOGGED_IN_USER_REQUEST'
export const VERIFY_LOGGED_IN_USER_SUCCESS = 'VERIFY_LOGGED_IN_USER_SUCCESS'
export const VERIFY_LOGGED_IN_USER_FAIL = 'VERIFY_LOGGED_IN_USER_FAIL'

export const LOGIN_WITH_EMAIL_REQUEST = 'LOGIN_WITH_EMAIL_REQUEST'
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS'
export const LOGIN_WITH_EMAIL_FAILURE = 'LOGIN_WITH_EMAIL_FAILURE'
