export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const NEW_GOOGLE_REGISTER_REQUEST = 'NEW_GOOGLE_REGISTER_REQUEST'
export const NEW_GOOGLE_REGISTER_SUCCESS = 'NEW_GOOGLE_REGISTER_SUCCESS'
export const NEW_GOOGLE_REGISTER_FAIL = 'NEW_GOOGLE_REGISTER_FAIL'
export const SET_GOOGLE_ACCOUNT_TYPE = 'SET_GOOGLE_ACCOUNT_TYPE'

export const CREATE_REAL_GOOGLE_ACCOUNT_REQUEST =
  'CREATE_GOOGLE_ACCOUNT_REQUEST'
export const CREATE_REAL_GOOGLE_ACCOUNT_SUCCESS = 'CREATE_REAL_GOOGLE_ACCOUNT_SUCCESS'
export const CREATE_REAL_GOOGLE_ACCOUNT_FAIL = 'CREATE_REAL_GOOGLE_ACCOUNT_FAIL'
