export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const NEW_GOOGLE_REGISTER_REQUEST = 'NEW_GOOGLE_REGISTER_REQUEST'
export const NEW_GOOGLE_REGISTER_SUCCESS = 'NEW_GOOGLE_REGISTER_SUCCESS'
export const NEW_GOOGLE_REGISTER_FAIL = 'NEW_GOOGLE_REGISTER_FAIL'
export const SET_GOOGLE_ACCOUNT_TYPE = 'SET_GOOGLE_ACCOUNT_TYPE'

export const CREATE_REAL_GOOGLE_ACCOUNT_REQUEST =
  'CREATE_GOOGLE_ACCOUNT_REQUEST'
export const CREATE_REAL_GOOGLE_ACCOUNT_SUCCESS =
  'CREATE_REAL_GOOGLE_ACCOUNT_SUCCESS'
export const CREATE_REAL_GOOGLE_ACCOUNT_FAIL = 'CREATE_REAL_GOOGLE_ACCOUNT_FAIL'

export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST'
export const LOGIN_GOOGLE_SUCCESS = 'LOGIN_GOOGLE_SUCCESS'
export const LOGIN_GOOGLE_FAIL = 'LOGIN_GOOGLE_FAIL'

export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'
